package org.usfirst.frc.team2974.robot;

import edu.wpi.first.wpilibj.Encoder;

import edu.wpi.first.wpilibj.AnalogInput;
import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.Relay;
import edu.wpi.first.wpilibj.VictorSP;
import edu.wpi.first.wpilibj.Relay.Direction;
import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
	public static Talon driveTrainFrontRight;
    public static Talon driveTrainBackRight;
    public static Talon driveTrainFrontLeft;
    public static Talon driveTrainBackLeft;
	
    public static Encoder encoderLeft;
    public static Encoder encoderRight;
    public static DigitalInput digital0;
    public static DigitalInput digital1;
    public static DigitalInput digital2;
    public static DigitalInput digital3;
    public static DigitalInput digital4;
    public static DigitalInput digital5;
    public static DigitalInput digital6;
    public static DigitalInput digital7;
    public static DigitalInput digital8;
    public static DigitalInput digital9;
    
    public static AnalogInput analog0;
    public static AnalogInput analog1;
    public static AnalogInput analog2;
    public static AnalogInput analog3;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
       
    	driveTrainFrontRight = new Talon(3);
        //LiveWindow.addActuator("DriveTrain", "FrontRight", (VictorSP) driveTrainFrontRight);
        
        driveTrainBackRight = new Talon(2);
        //LiveWindow.addActuator("DriveTrain", "BackRight", (VictorSP) driveTrainBackRight);
        
        driveTrainFrontLeft = new Talon(1);
        //LiveWindow.addActuator("DriveTrain", "FrontLeft", (VictorSP) driveTrainFrontLeft);
        
        driveTrainBackLeft = new Talon(0);
        //LiveWindow.addActuator("DriveTrain", "BackLeft", (VictorSP) driveTrainBackLeft);
            	
    	
    	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        
        digital0 = new DigitalInput(0);
        digital1 = new DigitalInput(1);
        digital2 = new DigitalInput(2);
        digital3 = new DigitalInput(3);
        digital4 = new DigitalInput(4);
        digital5 = new DigitalInput(5);
        digital6 = new DigitalInput(6);
        digital7 = new DigitalInput(7);
        digital8 = new DigitalInput(8);
        digital9 = new DigitalInput(9);
        
        analog0 = new AnalogInput(0);
        analog1 = new AnalogInput(1);
        analog2 = new AnalogInput(2);
        analog3 = new AnalogInput(3);
        

        encoderLeft = new Encoder(digital0,digital1);
        encoderRight = new Encoder(digital2,digital3);
        
    }
}
