package org.usfirst.frc.team2974.logging.enumerations;

public enum DriveTrain {
MOTION_CONTROL_STOPPED,
MOTION_CONTROL_BREAKING,
MOTION_CONTROL_MOVING,
MANUAL_MOVING,
MANUAL_STOPPED,
MANUAL_BREAKING
};
